"""The content-shape gate — is what we read the document, or a reference to one?

content-shape-gate D3 / plan action A3.

Three altitudes, and the split is the same one the sibling admission suites use:

* **Predicate level** — the pure function, driven on the REAL bytes of a real
  synced-drive placeholder taken off this machine and on the real git-LFS pointer
  form, plus the must-NOT-refuse cases at BOTH error directions.
* **Port level** — both path-shaped adapters driven THROUGH ``admit()``, never
  called directly, asserting the refusal reaches a RECORDED degradation rather
  than merely being returned, and that a non-path-shaped kind inherits nothing.
* **Caller level** — the refusal renders into the report body through the same
  channel the PDF refusal already uses, because to a person it is the same event.

**Why the must-not-refuse cases matter more than the refusals.** The refusals are
easy; the failure this slice could ship is over-refusal. Both directions are
guarded by DIFFERENT mechanisms and each has its own test: a ~50-byte genuine
note is below any conceivable size cap and survives only because every shape test
names a concrete shape, while a large JSON legitimately carrying ``doc_id``
matches a shape exactly and survives only because of the cap. A suite testing one
direction would pass with a predicate that is wrong in the other.
"""

from __future__ import annotations

import ast
import inspect
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from _source_guard import code_without_docstrings

CONFIG_DIR = Path(os.environ.get("CLAUDE_CONFIG_DIR", Path.home() / ".claude"))
sys.path.insert(0, str(CONFIG_DIR / "skills"))

from research import admission_record as arec                        # noqa: E402
from research import content_shape as cs                             # noqa: E402
from research import declared_read as dr                             # noqa: E402
from research import scope_record as srec                            # noqa: E402
from research import source_port as sp                               # noqa: E402
from research.adapters.document_folder import DocumentFolderAdapter  # noqa: E402
from research.adapters.knowledge_library import KnowledgeLibraryAdapter  # noqa: E402

PATH_SHAPED_KINDS = ("knowledge_library", "document_folder")

_ADAPTERS = {
    "knowledge_library": KnowledgeLibraryAdapter,
    "document_folder": DocumentFolderAdapter,
}
_SCOPES = {
    "knowledge_library": srec.knowledge_library_scope,
    "document_folder": srec.document_folder_scope,
}

# The REAL bytes of a real placeholder off this machine — 180 bytes, recorded in
# `research-source-adapters-20260829002225_DISCOVERY_WIP_4b796aef.md` §2. The
# document id is elided; nothing in the predicate reads its value.
REAL_DRIVE_STUB = (
    '{"": "WARNING! DO NOT EDIT THIS FILE! ANY CHANGES MADE WILL BE LOST!", '
    '"doc_id": "1QvMu0jYaKQ3xnR8pLd2fVhT7wZmB4cXeN6sGiUyOoAk", '
    '"resource_key": "", "email": "user@example.com"}'
)

# The real pointer form, per the git-LFS pointer-file spec.
REAL_LFS_POINTER = (
    "version https://git-lfs.github.com/spec/v1\n"
    "oid sha256:4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393\n"
    "size 12345\n"
)

# A genuine one-line note. ~50 bytes — BELOW any cap, so only signature
# specificity can save it.
GENUINE_SHORT_NOTE = "Ask Anna about the Q3 pricing model before Friday.\n"


def _port():
    return sp.AdmissionPort(arec.InMemoryAdmissionRecordStore())


def _item(kind, target):
    return sp.SourceItem(item_id=str(Path(target).resolve()), kind=kind,
                         target=str(target), depth=0)


def _git(cwd, *args):
    return subprocess.run(["git", "-C", str(cwd), *args],
                          capture_output=True, text=True, check=True).stdout.strip()


# =========================================================================== #
# Predicate level — the shapes it must catch
# =========================================================================== #

def test_the_real_drive_placeholder_bytes_are_not_the_document():
    """The exact bytes that were driven through the shipped adapter and admitted."""
    assert len(REAL_DRIVE_STUB.encode("utf-8")) < 256, "the real stub is small"
    reason = cs.not_the_document(REAL_DRIVE_STUB)
    assert reason, "the real placeholder was accepted as a document"
    assert "placeholder" in reason


def test_the_real_lfs_pointer_form_is_not_the_document():
    reason = cs.not_the_document(REAL_LFS_POINTER)
    assert reason, "an LFS pointer was accepted as a document"
    assert "LFS" in reason


@pytest.mark.parametrize("text", ["", "   ", "\n\n", "\t \n  \n"])
def test_empty_and_whitespace_only_are_not_the_document(text):
    """The LIVE case. An empty file costs no bytes, so it trips neither budget,
    and today a library of them is admitted wholesale and cited at line 1."""
    assert cs.not_the_document(text) == cs.REASON_EMPTY


@pytest.mark.parametrize("text", [
    '<?xml version="1.0"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
    '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">'
    '<dict><key>URL</key><string>https://example.com/a</string></dict></plist>\n',
    "[InternetShortcut]\nURL=https://example.com/a\n",
    "[Desktop Entry]\nType=Link\nURL=https://example.com/a\n",
])
def test_a_shortcut_holding_a_link_is_not_the_document(text):
    reason = cs.not_the_document(text)
    assert reason, "a shortcut was accepted as the document it links to"
    assert "shortcut" in reason


def test_emptiness_is_not_subject_to_the_shape_catalog():
    """Emptiness is a UNIVERSAL test, not a signature — which is what makes the
    live case fully covered while placeholder coverage is limited to shapes the
    catalog names. If it were a `Shape` it would sit behind the size cap, which
    is harmless today and would silently stop being harmless if the cap moved."""
    assert cs.REASON_EMPTY not in [s.reason for s in cs.SHAPES]
    assert cs.not_the_document("") == cs.REASON_EMPTY


# =========================================================================== #
# Predicate level — what it must NOT catch (both error directions)
# =========================================================================== #

def test_a_genuine_one_line_note_survives_and_the_cap_is_not_what_saves_it():
    """The load-bearing must-not-refuse case.

    A ~50-byte note is FAR below any cap, so no upper bound could protect it.
    What protects it is that every shape test names a concrete shape.

    The second assertion is the one that bites, and it is not a restatement of
    the first: it calls each `Shape.matches` DIRECTLY, which is downstream of
    the cap, so the cap cannot contribute to the result. If the note survived
    only because `not_the_document` returned early on size, the first assertion
    would still pass and this one would fail.
    """
    assert len(GENUINE_SHORT_NOTE.encode("utf-8")) < 100
    assert cs.not_the_document(GENUINE_SHORT_NOTE) is None

    assert not any(shape.matches(GENUINE_SHORT_NOTE) for shape in cs.SHAPES), (
        "ordinary prose matched a shape signature — the note survives only by "
        "accident of the size cap, which cannot protect it")


def test_a_large_genuine_document_carrying_the_same_key_survives_by_the_cap():
    """The OTHER error direction, guarded by a different mechanism.

    A real JSON document legitimately carrying `doc_id` matches the placeholder
    signature exactly. The cap is what saves it, and nothing else can.
    """
    big = json.dumps({"doc_id": "x", "records": ["y" * 80 for _ in range(200)]})
    assert len(big.encode("utf-8")) > cs.MAX_SHAPE_BYTES
    assert cs.not_the_document(big) is None

    small = json.dumps({"doc_id": "x"})
    assert cs.not_the_document(small), (
        "the cap is the only thing distinguishing these two, so the small one "
        "must be caught or the previous assertion proves nothing")


@pytest.mark.parametrize("text", [
    "# Notes\n\nThe pricing model has three tiers.\n",
    "def login():\n    return True\n",
    "version 3 of the git-lfs migration plan is attached\n",
    "See https://git-lfs.github.com/spec/v1 for the pointer format.\n",
    "The config uses a doc_id field to address each record.\n",
    '["a", "b", "c"]\n',
    "key: value\nother: thing\n",
])
def test_ordinary_content_is_never_refused(text):
    """Prose that MENTIONS a shape is not that shape. The LFS test requires the
    fixed token at the START of the file; the placeholder test requires a JSON
    object rather than a sentence containing the key."""
    assert cs.not_the_document(text) is None, text


def test_the_predicate_never_raises_and_returns_a_reason_or_nothing():
    for text in ["\x00", "{", "{]", "[]", "null", "true", '"a string"',
                 "﻿", "a" * 100000]:
        out = cs.not_the_document(text)
        assert out is None or isinstance(out, str)


# =========================================================================== #
# Predicate level — content, never location (the mirrored design-A31 guard)
# =========================================================================== #

def test_the_predicate_cannot_branch_on_location_because_it_never_sees_one():
    """The structural half. The defect exists because something inferred content
    from location; the strongest available guard is that the function has no
    location to inspect. A path parameter cannot be added without changing this
    signature, so this test fails before any location branch can be written."""
    params = list(inspect.signature(cs.not_the_document).parameters)
    assert params == ["content"], (
        f"not_the_document grew a parameter beyond the text: {params}")


def test_no_location_branch_exists_in_the_predicate_module():
    """The design-A31 AST guard, mirrored onto this module.

    `test_local_file_admission.py` asserts the document-folder adapter contains
    no mount detection and no provider path token, because a branch testing for
    one would make "ordinary" conditional on passing a test. The same must hold
    here: this module recognises SHAPES IN BYTES, and a provider path or a mount
    test would reintroduce exactly the inference the slice removes.
    """
    src = (CONFIG_DIR / "skills" / "research" / "content_shape.py").read_text()
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            name = getattr(node.func, "attr", None) or getattr(node.func, "id", None)
            assert name not in ("is_mount", "is_dir", "is_file", "exists",
                                "stat", "resolve", "expanduser"), (
                f"the predicate inspects the filesystem via {name!r}")

    # The token half scans the WHOLE body, docstrings excluded. The original
    # guard used `split('"""')[-1]`, which returns the text after the LAST
    # triple quote rather than after the module docstring — on this module that
    # was 9 of 190 lines, so a provider list added inside a shape function would
    # have passed untouched. See `_source_guard` for the measurement.
    body = code_without_docstrings(src)
    assert "_is_drive_placeholder" in body, (
        "the scanned body no longer reaches the shape functions, which is where "
        "a location branch would be added — the guard has gone hollow again")
    for token in ("CloudStorage", "GoogleDrive", "Dropbox", "OneDrive",
                  "suffix", "Path", "os.path"):
        assert token not in body, f"the predicate branches on location via {token!r}"


def test_the_catalog_is_extensible_without_touching_the_port():
    """A shape nobody has taught it yet passes unrefused — that is the disclosed
    residue of choosing specificity over guessing. Adding one must be a new row
    here and nothing else, which is what this asserts: the port names no shape."""
    unknown = "PLACEHOLDER-FORMAT-NOBODY-HAS-TAUGHT-THIS-TOOL\nref: 12345\n"
    assert cs.not_the_document(unknown) is None, (
        "an uncatalogued shape was caught — good, but then this test's premise "
        "is stale and the disclosed limit needs rewording")

    port_src = (CONFIG_DIR / "skills" / "research" / "source_port.py").read_text()
    for shape in cs.SHAPES:
        assert shape.name not in port_src, (
            f"the port names the shape {shape.name!r}; adding a shape would "
            "then require touching the port")


# =========================================================================== #
# Port level — one gated site, both path-shaped adapters, through admit()
# =========================================================================== #

@pytest.fixture()
def folder(tmp_path):
    root = tmp_path.resolve()
    declared = root / "<KL>" / "Dev"
    declared.mkdir(parents=True)
    return root, declared


@pytest.mark.parametrize("kind", PATH_SHAPED_KINDS)
def test_an_empty_file_is_refused_by_name_through_the_port(kind, folder):
    """The live case, at the altitude that matters. Before this slice the file
    was admitted with `line = "1"` and cited as a source with nothing behind it."""
    root, declared = folder
    empty = declared / "german_care_workforce_PHASE2_RESEARCH.md"
    empty.write_text("")
    scope = _SCOPES[kind]([declared])
    adapter = _ADAPTERS[kind](projects_root=root)

    result = _port().admit(_item(kind, empty), scope, adapter, run_id="r")

    assert not result.admitted, "an empty file was admitted and would be cited"
    assert result.degradation.obligation == sp.OBLIGATION_READABLE
    assert result.degradation.reason == cs.REASON_EMPTY
    assert result.pin is None, "a refused item must carry no pin"
    assert result.content in (None, ""), "a refused item must carry no content"


@pytest.mark.parametrize("kind", PATH_SHAPED_KINDS)
def test_a_placeholder_is_refused_while_its_real_sibling_still_reads(kind, folder):
    """The inversion pair, at port level.

    The census found a real folder where the PDF (the document) is refused by
    name and the placeholder (the pointer) is silently cited. Both halves are
    asserted together on purpose: a predicate that refused everything would pass
    the first assertion alone.
    """
    root, declared = folder
    (declared / "Case_Study.gdoc").write_text(REAL_DRIVE_STUB)
    (declared / "Case_Study.md").write_text("# Case study\n\nThe real thing.\n")
    scope = _SCOPES[kind]([declared])
    adapter = _ADAPTERS[kind](projects_root=root)
    port = _port()

    stub = port.admit(_item(kind, declared / "Case_Study.gdoc"), scope, adapter,
                      run_id="r")
    assert not stub.admitted, "the placeholder was admitted"
    assert stub.degradation.obligation == sp.OBLIGATION_READABLE

    real = port.admit(_item(kind, declared / "Case_Study.md"), scope, adapter,
                      run_id="r")
    assert real.admitted, (
        f"the real sibling was refused too: {real.degradation}")
    assert "The real thing." in real.content


@pytest.mark.parametrize("kind", PATH_SHAPED_KINDS)
def test_the_refusal_is_a_recorded_degradation_not_merely_a_return(kind, folder):
    """`admit()` persists its own outcome before returning. A refusal that were
    only returned would leave no trail for `list_degradations` — the retrieval a
    later slice's integrity accounting reads."""
    root, declared = folder
    (declared / "empty.md").write_text("")
    scope = _SCOPES[kind]([declared])
    adapter = _ADAPTERS[kind](projects_root=root)
    store = arec.InMemoryAdmissionRecordStore()

    sp.AdmissionPort(store).admit(_item(kind, declared / "empty.md"), scope,
                                  adapter, run_id="run-1")

    recorded = store.list_degradations("run-1")
    assert len(recorded) == 1, "the refusal left no record"
    assert recorded[0].obligation == sp.OBLIGATION_READABLE
    assert recorded[0].reason == cs.REASON_EMPTY


@pytest.mark.parametrize("kind", PATH_SHAPED_KINDS)
def test_a_genuine_short_note_is_still_admitted_through_the_port(kind, folder):
    """The must-not-refuse case at port level, not only at predicate level."""
    root, declared = folder
    note = declared / "note.md"
    note.write_text(GENUINE_SHORT_NOTE)
    scope = _SCOPES[kind]([declared])
    adapter = _ADAPTERS[kind](projects_root=root)

    result = _port().admit(_item(kind, note), scope, adapter, run_id="r")

    assert result.admitted, f"a genuine short note was refused: {result.degradation}"
    assert result.content == GENUINE_SHORT_NOTE


def test_the_check_is_wired_at_exactly_one_site():
    """A2's guard rail. The whole reason the check is in the port rather than in
    each adapter is that a per-adapter copy would drift; asserting one call site
    is what keeps that true as adapters are added."""
    port_src = (CONFIG_DIR / "skills" / "research" / "source_port.py").read_text()
    calls = [n for n in ast.walk(ast.parse(port_src))
             if isinstance(n, ast.Call)
             and (getattr(n.func, "id", None) == "not_the_document"
                  or getattr(n.func, "attr", None) == "not_the_document")]
    assert len(calls) == 1, f"expected exactly one call site, found {len(calls)}"

    for module in ("document_folder", "knowledge_library", "code_base", "linear",
                   "web"):
        src = (CONFIG_DIR / "skills" / "research" / "adapters"
               / f"{module}.py").read_text()
        assert "not_the_document" not in src, (
            f"{module} calls the predicate directly; the port owns this decision")


def test_a_non_path_shaped_kind_inherits_nothing_from_this_gate():
    """The gate is what keeps the kind-generic check from colliding with a
    kind-specific one an adapter already owns. `linear` is `path_shaped=False`
    and keeps its own emptiness refusal; a future non-path-shaped kind will need
    its own, and nothing here will remind the implementer — which is why the
    residual is recorded at the call site."""
    assert sp.rules_for("linear").path_shaped is False
    linear_src = (CONFIG_DIR / "skills" / "research" / "adapters"
                  / "linear.py").read_text()
    assert "not_the_document" not in linear_src
    assert "if not content:" in linear_src, (
        "linear's own kind-specific emptiness check was removed")


def test_an_unregistered_kind_inherits_the_gate():
    """`_DEFAULT_KIND_RULES.path_shaped` is True, so a kind with no registered
    rules gets the check with no edit — the Evolution-test half of why A2 places
    this in the port."""
    assert sp.rules_for("a-kind-nobody-registered").path_shaped is True


# =========================================================================== #
# Port level — the `code` kind, against a real repository
# =========================================================================== #

@pytest.fixture()
def repo(tmp_path):
    """A real git repository with one commit — the only fixture here that
    exercises `code_base.py`, which is a direct `SourceAdapter` subclass and
    inherits nothing from the document-folder adapter."""
    root = (tmp_path / "widget-service").resolve()
    root.mkdir()
    _git(root, "init", "-q")
    _git(root, "config", "user.email", "t@example.invalid")
    _git(root, "config", "user.name", "T")
    (root / "auth.py").write_text("def login():\n    return True\n")
    (root / "asset.bin").write_text(REAL_LFS_POINTER)
    (root / "blank.py").write_text("")
    _git(root, "add", "-A")
    _git(root, "commit", "-qm", "first")
    return root


def test_an_lfs_pointer_in_a_real_repository_is_refused_and_real_code_still_reads(repo):
    """Both halves together. `code` only became reachable in production recently
    and an LFS pointer is ordinary text in a working tree, so this is the forward
    risk rather than a live one — which is exactly why it needs a test."""
    result = dr.read_declared_sources(srec.code_scope([repo]), projects_root=repo)

    read = sorted(Path(r.item).name for r in result.readings)
    refused = {Path(r.item).name: r for r in result.refusals}

    assert "auth.py" in read, (
        f"real code stopped reading; refusals were "
        f"{[r.render() for r in result.refusals]}")
    assert "asset.bin" in refused, "an LFS pointer was read as though it were the object"
    assert refused["asset.bin"].obligation == sp.OBLIGATION_READABLE
    assert "LFS" in refused["asset.bin"].reason

    assert "blank.py" in refused, "an empty file in a repository was admitted"
    assert refused["blank.py"].reason == cs.REASON_EMPTY


# =========================================================================== #
# Caller level — the refusal reaches the person, in the PDF's channel
# =========================================================================== #

def test_the_refusal_reaches_the_report_body_exactly_as_a_pdf_refusal_does(folder):
    """C3. To a person this is the same event as an unreadable PDF: a file you
    pointed me at could not be read, and here is which one. So it must arrive
    through the same channel, at the same point, wearing the same obligation —
    the assertion is that the two renderings are indistinguishable in shape."""
    root, declared = folder
    (declared / "empty_research.md").write_text("")
    (declared / "scan.pdf").write_bytes(b"%PDF-1.4\n\x80\x81\x82 binary\n")
    (declared / "real.md").write_text("# Real\n\nSomething to find.\n")

    result = dr.read_declared_sources(
        srec.document_folder_scope([declared]), projects_root=root)

    rendered = {Path(r.item).name: r.render() for r in result.refusals}
    assert "empty_research.md" in rendered, (
        f"the empty file was not refused by name; refusals were {rendered}")
    assert "scan.pdf" in rendered, "the PDF control did not refuse"

    empty_line, pdf_line = rendered["empty_research.md"], rendered["scan.pdf"]
    for line in (empty_line, pdf_line):
        assert line.startswith("refused: ")
        assert line.endswith(f"[{sp.OBLIGATION_READABLE}]")

    body = dr.synthesize_from_admissions(result)
    assert "empty_research.md" in body, (
        "the refusal never reached the body, so a person is told nothing")
    assert "Something to find." in body, "the real file stopped reaching the body"


def test_the_person_is_told_what_to_do_about_it(folder):
    """C5. Being told is what lets them act — convert the file, point somewhere
    else, or knowingly accept the gap. A reason naming only the failure would
    satisfy the letter of "loud" and none of its purpose."""
    root, declared = folder
    (declared / "Case_Study.gdoc").write_text(REAL_DRIVE_STUB)

    result = dr.read_declared_sources(
        srec.document_folder_scope([declared]), projects_root=root)

    reasons = " ".join(r.reason for r in result.refusals)
    assert "export or download" in reasons, (
        f"the refusal names no remedy: {reasons}")
